__2020.03.24 WerldDoMetersCorona_Scraping__

Gather the all Municipalities name

In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import date, timedelta 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
url='https://www.worldometers.info/coronavirus/#countries'
r=requests.get(url)
soup = BeautifulSoup(r.text,'html.parser')
#class="wikitable plainrowheaders sortable jquery-tablesorter"
table=soup.find('table',{'id':'main_table_countries_yesterday'})
rows=table.find_all('tr')[1:]
rows[1]

<tr style="">
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/china/">China</a></td>
<td style="font-weight: bold; text-align:right">81,639</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+19</td>
<td style="font-weight: bold; text-align:right;">3,326 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+4</td>
<td style="font-weight: bold; text-align:right">76,755</td>
<td style="text-align:right;font-weight:bold;">1,558</td>
<td style="font-weight: bold; text-align:right">331</td>
<td style="font-weight: bold; text-align:right">57</td>
<td style="font-weight: bold; text-align:right">2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
</tr>

In [3]:
italy=0
usa=0
spain=0
germany=0
france=0
switzerland=0
uk=0
netherlands=0
aantalen=[]
yesterday = date.today() - timedelta(days=1)
yesterday=yesterday.strftime("%m/%d/%Y")
aantalen.append(str(yesterday))
#country_names=['Italy','USA','Spain','Germany','France','Switzerland','UK','Netherlands']
for row in rows:   
    country=row.find_all('td')[0].text.strip() # The column of Country Names 
    #print(country)
    aantal=row.find_all('td')[2].text.strip() #the Column of Daily New Cases 
    #print(aantal)
    #!!!!!! IMPORTANT: Aşağıdaki Sıralamayı değiştirmeyin
    if country == 'Italy':
        italy = aantal.replace(",", "")
        italy = italy.replace("+", "")
    if country == 'USA':
        usa = aantal.replace(",", "")
        usa = usa.replace("+", "")
    if country == 'Spain':
        spain= aantal.replace(",", "")
        spain = spain.replace("+", "")
    if country == 'Germany':
        germany=aantal.replace(",", "")
        germany = germany.replace("+", "")
    if country == 'France':
        france = aantal.replace(",", "")
        france = france.replace("+", "")
    if country == 'Switzerland':
        switzerland = aantal.replace(",", "")
        switzerland = switzerland.replace("+", "")
    if country == 'UK':
        uk = aantal.replace(",", "")
        uk = uk.replace("+", "")
    if country == 'Netherlands':
        netherlands = aantal.replace(",", "")
        netherlands = netherlands.replace("+", "")
aantalen.append(italy)
aantalen.append(usa)
aantalen.append(spain)
aantalen.append(germany)
aantalen.append(france)
aantalen.append(switzerland)
aantalen.append(uk)
aantalen.append(netherlands)


#print(countries)
print(aantalen)

['04/04/2020', '4805', '34196', '6969', '4933', '7788', '899', '3735', '904']

In [4]:
#importing the corona aatal van de landen
df = pd.read_csv('output/corona_dailyNewCases.csv',index_col=0)
df = df.drop_duplicates()
df

,date,Italy,USA,Spain,Germany,France,Switzerland,UK,Netherlands
0,02/15/2020,0,0,0,0,0,0,0,0
1,02/16/2020,0,0,0,0,0,0,0,0
2,02/17/2020,0,0,0,0,0,0,0,0
3,02/18/2020,0,0,0,0,0,0,0,0
4,02/19/2020,0,0,0,0,0,0,0,0
5,02/20/2020,1,0,0,0,0,0,0,0
6,02/21/2020,17,20,0,0,0,0,0,0
7,02/22/2020,58,0,0,0,0,0,0,0
8,02/23/2020,78,0,0,0,0,0,4,0
9,02/24/2020,72,18,1,0,0,0,0,0
10,02/25/2020,94,4,6,2,2,0,0,0
11,02/26/2020,147,3,4,8,4,0,0,0
12,02/27/2020,185,0,12,22,20,7,3,0
13,02/28/2020,234,3,8,26,19,7,4,1
14,02/29/2020,239,5,25,5,43,4,3,5
15,03/01/2020,573,7,26,51,30,5,13,3
16,03/02/2020,335,25,36,35,61,6,3,8
17,03/03/2020,466,24,45,38,21,28,12,5
18,03/04/2020,587,34,63,59,73,35,36,15
19,03/05/2020,769,63,54,283,138,27,29,44
20,03/06/2020,778,98,119,125,230,94,48,46
21,03/07/2020,1247,116,124,130,296,54,45,60
22,03/08/2020,1492,106,149,240,260,64,69,77
23,03/09/2020,1797,163,557,184,203,42,43,56
24,03/10/2020,977,290,464,341,372,123,62,61
25,03/11/2020,2313,307,582,401,497,155,77,121
26,03/12/2020,2651,329,869,779,595,216,130,111
27,03/13/2020,2547,553,2086,930,785,271,208,190
28,03/14/2020,3497,587,1159,924,838,236,342,155
29,03/15/2020,3590,843,1597,1214,924,842,251,176
30,03/16/2020,3233,983,1954,1459,1210,136,152,278
31,03/17/2020,3526,1748,1884,2095,1097,389,407,292
32,03/18/2020,4207,2853,2943,2960,1404,373,676,346
33,03/19/2020,5322,4582,3308,2993,1861,1107,643,409
34,03/20/2020,5986,5588,3494,4528,1617,1393,714,534
35,03/21/2020,6557,4825,3925,2516,1847,1248,1035,637
36,03/22/2020,5560,9400,3272,2509,1559,611,665,573
37,03/23/2020,4789,10189,6368,4183,3838,1321,967,545
38,03/24/2020,5249,11075,6922,3935,2448,1082,1427,811
39,03/25/2020,5210,13355,7457,4332,2929,1020,1452,852
40,03/26/2020,6203,17224,8271,6615,3922,914,2129,1019
41,03/27/2020,5909,18691,7933,6933,3809,1117,2885,1172
42,03/28/2020,5974,19452,7516,6824,4611,1148,2546,1159
43,03/29/2020,5217,19913,6875,4740,2599,753,2433,1104
44,03/30/2020,4050,20297,7846,4450,4376,1093,2619,884
45,03/31/2020,4053,24742,7967,4923,7578,683,3009,845
46,04/01/2020,4782,26473,8195,6173,4861,1163,4324,1019
47,04/02/2020,4668,29874,7947,6813,2116,1059,4244,1083

In [5]:
aantalen[0] in str(df['date'])

False

In [6]:
if aantalen[0] in str(df['date']):
    print('data is already updated!')
else:    
    df.loc[len(df)] = aantalen
    df.to_csv('output/corona_dailyNewCases.csv')
    print('data is saved')

data is saved

In [7]:
df

          date Italy    USA Spain Germany France Switzerland    UK Netherlands
0   02/15/2020     0      0     0       0      0           0     0           0
1   02/16/2020     0      0     0       0      0           0     0           0
2   02/17/2020     0      0     0       0      0           0     0           0
3   02/18/2020     0      0     0       0      0           0     0           0
4   02/19/2020     0      0     0       0      0           0     0           0
5   02/20/2020     1      0     0       0      0           0     0           0
6   02/21/2020    17     20     0       0      0           0     0           0
7   02/22/2020    58      0     0       0      0           0     0           0
8   02/23/2020    78      0     0       0      0           0     4           0
9   02/24/2020    72     18     1       0      0           0     0           0
10  02/25/2020    94      4     6       2      2           0     0           0
11  02/26/2020   147      3     4       8      4           0     0           0
12  02/27/2020   185      0    12      22     20           7     3           0
13  02/28/2020   234      3     8      26     19           7     4           1
14  02/29/2020   239      5    25       5     43           4     3           5
15  03/01/2020   573      7    26      51     30           5    13           3
16  03/02/2020   335     25    36      35     61           6     3           8
17  03/03/2020   466     24    45      38     21          28    12           5
18  03/04/2020   587     34    63      59     73          35    36          15
19  03/05/2020   769     63    54     283    138          27    29          44
20  03/06/2020   778     98   119     125    230          94    48          46
21  03/07/2020  1247    116   124     130    296          54    45          60
22  03/08/2020  1492    106   149     240    260          64    69          77
23  03/09/2020  1797    163   557     184    203          42    43          56
24  03/10/2020   977    290   464     341    372         123    62          61
25  03/11/2020  2313    307   582     401    497         155    77         121
26  03/12/2020  2651    329   869     779    595         216   130         111
27  03/13/2020  2547    553  2086     930    785         271   208         190
28  03/14/2020  3497    587  1159     924    838         236   342         155
29  03/15/2020  3590    843  1597    1214    924         842   251         176
30  03/16/2020  3233    983  1954    1459   1210         136   152         278
31  03/17/2020  3526   1748  1884    2095   1097         389   407         292
32  03/18/2020  4207   2853  2943    2960   1404         373   676         346
33  03/19/2020  5322   4582  3308    2993   1861        1107   643         409
34  03/20/2020  5986   5588  3494    4528   1617        1393   714         534
35  03/21/2020  6557   4825  3925    2516   1847        1248  1035         637
36  03/22/2020  5560   9400  3272    2509   1559         611   665         573
37  03/23/2020  4789  10189  6368    4183   3838        1321   967         545
38  03/24/2020  5249  11075  6922    3935   2448        1082  1427         811
39  03/25/2020  5210  13355  7457    4332   2929        1020  1452         852
40  03/26/2020  6203  17224  8271    6615   3922         914  2129        1019
41  03/27/2020  5909  18691  7933    6933   3809        1117  2885        1172
42  03/28/2020  5974  19452  7516    6824   4611        1148  2546        1159
43  03/29/2020  5217  19913  6875    4740   2599         753  2433        1104
44  03/30/2020  4050  20297  7846    4450   4376        1093  2619         884
45  03/31/2020  4053  24742  7967    4923   7578         683  3009         845
46  04/01/2020  4782  26473  8195    6173   4861        1163  4324        1019
47  04/02/2020  4668  29874  7947    6813   2116        1059  4244        1083
48  04/04/2020  4805  34196  6969    4933   7788         899  3735         904