__2020.03.24 WerldDoMetersCorona_Scraping__

Gather the all Municipalities name

In [2]:
#import libraries
import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import date, timedelta, datetime, time 
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import time

In [3]:
#zaman=pd.to_datetime('now').strftime("%I.%M")
#zaman
#if time(10,30) <= now.time() <= time(16,30):
#<= time(16,30):   
#time(10,30) <= datetime.now()

In [17]:
# get the URL
url='https://www.worldometers.info/coronavirus/#countries'
r=requests.get(url)
soup = BeautifulSoup(r.text,'html.parser')
#get te table
table=soup.find('table',{'id':'main_table_countries_yesterday'})
rows=table.find_all('tr')[1:]

rows[1]

italy=0
usa=0
spain=0
germany=0
france=0
switzerland=0
uk=0
netherlands=0
aantalen=[]
# get the yesterday in format of Month / day / Year
yesterday = date.today() - timedelta(days=1)
yesterday=yesterday.strftime("%m/%d/%Y")
aantalen.append(str(yesterday))

#country_names=['Italy','USA','Spain','Germany','France','Switzerland','UK','Netherlands']
for row in rows:   
    country=row.find_all('td')[0].text.strip() # gettng the first column that is the countey name from the table
    #print(country)
    aantal=row.find_all('td')[1].text.strip() # getting the second column that is the nummers of the cases for each country 
    #print(aantal)
    if country == 'Italy':
        italy = aantal.replace(",", "")
    if country == 'USA':
        usa = aantal.replace(",", "")
    if country == 'Spain':
        spain= aantal.replace(",", "")
    if country == 'Germany':
        germany=aantal.replace(",", "")
    if country == 'France':
        france = aantal.replace(",", "")
    if country == 'Switzerland':
        switzerland = aantal.replace(",", "")
    if country == 'UK':
        uk = aantal.replace(",", "")
    if country == 'Netherlands':
        netherlands = aantal.replace(",", "")
    
           
#  !!!IMPORTANT!!! do not change the order below.  
aantalen.append(italy)
aantalen.append(usa)
aantalen.append(spain)
aantalen.append(germany)
aantalen.append(france)
aantalen.append(switzerland)
aantalen.append(uk)
aantalen.append(netherlands)


#print(countries)
#print(aantalen)
#importing the CSV file that has the corona aatal van de landen
df = pd.read_csv('output/corona.csv',index_col=0)
df = df.drop_duplicates()
#df
if aantalen[0] in str(df['date']): # if tha date of the new values is not in the date column of DataFrame,
    print('data is already updated!') # do not add the new data into DataFrame e
else:                                 # else
    print('New values: '+aantalen)
    df.loc[len(df)] = aantalen
    df.to_csv('output/corona.csv')
    df = pd.read_csv('output/corona.csv',index_col=0)
    df = df.drop_duplicates()
    print('data is saved')
    
    # calculating percentage for each country
    populations=[60480000,327200000,46660000,82790000,66890000,8560000,66440000,17180000]
    i=0
    df1=df
    for column in df.drop('date', axis=1):
        df1[column]= (df1[column].astype(int))/populations[i]
        i+=1
    df1.to_csv('output/corona%.csv')
df

data is already updated!

,date,Italy,USA,Spain,Germany,France,Switzerland,UK,Netherlands
0,02/15/2020,3,15,2,16,12,0,9,0
1,02/16/2020,3,15,2,16,12,0,9,0
2,02/17/2020,3,15,2,16,12,0,9,0
3,02/18/2020,3,15,2,16,12,0,9,0
4,02/19/2020,3,15,2,16,12,0,9,0
...,...,...,...,...,...,...,...,...,...
59,04/16/2020,168941,677570,184948,137698,165027,26732,103093,29214
60,04/17/2020,172434,709735,190839,141397,147969,27078,108692,30449
61,04/18/2020,175925,738792,194416,143724,151793,27404,114217,31589
62,04/19/2020,178972,764636,198674,145742,152894,27740,120067,32655
63,04/20/2020,181228,792759,200210,147065,155383,27944,124743,33405

# DailyNewCasesPerCountry_Scraping

In [20]:
url='https://www.worldometers.info/coronavirus/#countries'
r=requests.get(url)
soup = BeautifulSoup(r.text,'html.parser')
#class="wikitable plainrowheaders sortable jquery-tablesorter"
table=soup.find('table',{'id':'main_table_countries_yesterday'})
rows=table.find_all('tr')[1:]
rows[1]
italy=0
usa=0
spain=0
germany=0
france=0
switzerland=0
uk=0
netherlands=0
aantalen=[]
yesterday = date.today() - timedelta(days=1)
yesterday=yesterday.strftime("%m/%d/%Y")
aantalen.append(str(yesterday))
#country_names=['Italy','USA','Spain','Germany','France','Switzerland','UK','Netherlands']
for row in rows:   
    country=row.find_all('td')[0].text.strip() # The column of Country Names 
    #print(country)
    aantal=row.find_all('td')[2].text.strip() #the Column of Daily New Cases 
    #print(aantal)
    #!!!!!! IMPORTANT: AÅŸaÄŸÄ±daki SÄ±ralamayÄ± deÄŸiÅŸtirmeyin
    if country == 'Italy':
        italy = aantal.replace(",", "")
        italy = italy.replace("+", "")
    if country == 'USA':
        usa = aantal.replace(",", "")
        usa = usa.replace("+", "")
    if country == 'Spain':
        spain= aantal.replace(",", "")
        spain = spain.replace("+", "")
    if country == 'Germany':
        germany=aantal.replace(",", "")
        germany = germany.replace("+", "")
    if country == 'France':
        france = aantal.replace(",", "")
        france = france.replace("+", "")
    if country == 'Switzerland':
        switzerland = aantal.replace(",", "")
        switzerland = switzerland.replace("+", "")
    if country == 'UK':
        uk = aantal.replace(",", "")
        uk = uk.replace("+", "")
    if country == 'Netherlands':
        netherlands = aantal.replace(",", "")
        netherlands = netherlands.replace("+", "")

        
#  !!!IMPORTANT!!! do not change the order below.  
aantalen.append(italy)
aantalen.append(usa)
aantalen.append(spain)
aantalen.append(germany)
aantalen.append(france)
aantalen.append(switzerland)
aantalen.append(uk)
aantalen.append(netherlands)


#print(countries)

#importing the corona aatal van de landen
df = pd.read_csv('output/corona_dailyNewCases.csv',index_col=0)
df = df.drop_duplicates()
if aantalen[0] in str(df['date']):
    print('data is already updated!')
else:    
    print('New values: '+aantalen)
    df.loc[len(df)] = aantalen
    df.to_csv('output/corona_dailyNewCases.csv')
    print('data is saved')
    populations=[60480000,327200000,46660000,82790000,66890000,8560000,66440000,17180000]
    i=0
    df1=df
    for column in df.drop('date', axis=1):
        df1[column]= (df1[column].astype(int))/populations[i]
        i+=1
    df1.to_csv('output/corona_dailyNewCases%.csv')
df

data is already updated!

,date,Italy,USA,Spain,Germany,France,Switzerland,UK,Netherlands
0,02/15/2020,0,0,0,0,0,0,0,0
1,02/16/2020,0,0,0,0,0,0,0,0
2,02/17/2020,0,0,0,0,0,0,0,0
3,02/18/2020,0,0,0,0,0,0,0,0
4,02/19/2020,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
59,04/16/2020,3786,29567,4289,2945,17164,396,4617,1061
60,04/17/2020,3493,32165,5891,3699,1909,346,5599,1235
61,04/18/2020,3491,29057,3577,2327,3824,326,5525,1140
62,04/19/2020,3047,25844,4258,2018,1101,336,5850,1066
63,04/20/2020,2256,28123,1536,1323,2489,204,4676,750